[build]
  base = "/"
  publish = "/dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"

[context.production.environment]
  NODE_ENV = "production"
