[build]
  base = "/"
  publish = "dist"
  command = "rm -rf node_modules dist .vite && npm install --legacy-peer-deps && npm install vite@4.5.0 @vitejs/plugin-react@4.2.1 && npx vite@4.5.0 build"
  environment = { NODE_VERSION = "18" }
  [build.rollupOptions]
    external = ["vite", "react-native", "react-native-web"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:;"

[context.production.environment]
  NODE_ENV = "production"
